### ISSUE TITLE
你好，请问你使用的是那个模块

### ISSUE THREAD

**Issue by yujinqiao** [Liber-coder/MAX30102_demo_only_C#1]
你好，我想网上买了一个黑色的max30102模块，根据你的实现例程，在烧录进行以后，我确认接口没问题，但是烧录进去之后，得不到稳定的血氧和心率，一直显示-999

**Comment by Liber-coder** [comment]
我买的MAX30102是某宝重庆艾迪逊电子店铺的。只有5个引脚，VCC、GND、SCL、SDA、INT。建议你找店家要一下电路图，对比两个模块的硬件连接有什么不同 :)

**Comment by yangyongyong1** [comment]
> 你好，我想网上买了一个黑色的max30102模块，根据你的实现例程，在烧录进行以后，我确认接口没问题，但是烧录进去之后，得不到稳定的血氧和心率，一直显示-999

我想问问您，问题解决了没有，我也是黑色的max30102，读出来也是-999，想问问您怎么解决的。。。
