### ISSUE TITLE
你好，我用你的程序，测出来的心率和血氧都是-999

### ISSUE THREAD

**Issue by yuan-yuan-jia** [Liber-coder/MAX30102_demo_only_C#2]
你好，我用你的程序，测出来的心率和血氧都是-999

**Comment by Liber-coder** [comment]
工程许多人用过了没问题，估计还是硬件问题。或许你可以换一个其他类型的MAX30102模块试试

**Comment by Liber-coder** [comment]
> 你好，我用你的程序，测出来的心率和血氧都是-999

这里有人解决了，可能对你会有帮助：
[太坑了！-999的原因找到了](https://github.com/KNLc/MAX30102_demo_only_C/issues/3#issuecomment-620654931) | 这里说是IIC或引脚连接问题
[血氧 -999 问题找到了](https://github.com/KNLc/MAX30102_demo_only_C/issues/5#issue-655402684) | 这里说是因为新老版本fifo问题
