### ISSUE TITLE
太坑了！-999的原因找到了

### ISSUE THREAD

**Issue by 2015-INSPIRER** [Liber-coder/MAX30102_demo_only_C#3]

**Comment by 2015-INSPIRER** [comment]
while(max30102_INTPin==1);   //等待MAX30102中断引脚拉低

把1改成0就好了、、、、
难道是不同的模块硬件不一样？
我用的是那种绿色的7针的
我看了两个视频都是黑色4*2针的

**Comment by Liber-coder** [comment]
> while(max30102_INTPin==1); //等待MAX30102中断引脚拉低
> 
> 把1改成0就好了、、、、
> 难道是不同的模块硬件不一样？
> 我用的是那种绿色的7针的
> 我看了两个视频都是黑色4*2针的

谢谢分享，你的回答可能对其他人有帮助。
应该是硬件连接不同，我猜测可能你的7针模块没有引出INT引脚？

**Comment by yangyongyong1** [comment]
您好，我用的黑色的max30102，也是读出来-999，按照你上面说的吧while（max30102_INTPin == 1）; //等待MAX30102中断中断拉低，把他换成0，也不对，想问问您还有其他办法么？非常感谢

**Comment by 2015-INSPIRER** [comment]
那肯定是这代码的IIC驱动有问题    从别处移植一下吧
我用的F407   移植了IIC驱动
最后也测不准   估计算法还要调吧

**Comment by yangyongyong1** [comment]
我也是用的F407，结果收到的都是999和0，唉，------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;2015-INSPIRER&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月7日(星期二) 下午3:27
收件人:&nbsp;&quot;KNLc/MAX30102_demo_only_C&quot;<MAX30102_demo_only_C@noreply.github.com&gt;;
抄送:&nbsp;&quot;yangyongyong1&quot;<823940465@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [KNLc/MAX30102_demo_only_C] 太坑了！-999的原因找到了 (#3)

**Comment by yangyongyong1** [comment]
您的iic能不能给我发一下。我换了好几个IIc得了，哎，难受啊


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "2015-INSPIRER"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 下午3:27
收件人: "KNLc/MAX30102_demo_only_C"<MAX30102_demo_only_C@noreply.github.com&gt;; 
抄送: "杨勇勇"<823940465@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [KNLc/MAX30102_demo_only_C] 太坑了！-999的原因找到了 (#3)



那肯定是这代码的IIC驱动有问题从别处移植一下吧
 我用的F407 移植了IIC驱动
 最后也测不准 估计算法还要调吧
